package entidades;
// Generated 16/11/2019 11:28:39 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auditoria generated by hbm2java
 */
@Entity
@Table(name = "auditoria", catalog = "BtB9DLrhnQ")
public class Auditoria implements java.io.Serializable {

	private int id;
	private String userId;
	private String operationCrud;
	private String tableName;
	private int tableId;
	private Date createDate;
	private String addressIp;

	public Auditoria() {
	}

	public Auditoria(int id, String userId, String operationCrud, String tableName, int tableId, Date createDate,
			String addressIp) {
		this.id = id;
		this.userId = userId;
		this.operationCrud = operationCrud;
		this.tableName = tableName;
		this.tableId = tableId;
		this.createDate = createDate;
		this.addressIp = addressIp;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "userId", nullable = false, length = 8)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "operationCrud", nullable = false, length = 20)
	public String getOperationCrud() {
		return this.operationCrud;
	}

	public void setOperationCrud(String operationCrud) {
		this.operationCrud = operationCrud;
	}

	@Column(name = "tableName", nullable = false, length = 30)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "tableId", nullable = false)
	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "addressIP", nullable = false, length = 70)
	public String getAddressIp() {
		return this.addressIp;
	}

	public void setAddressIp(String addressIp) {
		this.addressIp = addressIp;
	}

}
