package entidades;
// Generated 16/11/2019 11:28:39 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "clientes", catalog = "BtB9DLrhnQ")
public class Clientes implements java.io.Serializable {

	private Long id;
	private String apellidos;
	private String direccion;
	private String email;
	private Date factualizar;
	private Date fregistro;
	private String nombres;
	private String telefono;

	public Clientes() {
	}

	public Clientes(String apellidos, String direccion, String email, Date factualizar, Date fregistro, String nombres,
			String telefono) {
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.email = email;
		this.factualizar = factualizar;
		this.fregistro = fregistro;
		this.nombres = nombres;
		this.telefono = telefono;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "apellidos")
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "factualizar", length = 26)
	public Date getFactualizar() {
		return this.factualizar;
	}

	public void setFactualizar(Date factualizar) {
		this.factualizar = factualizar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fregistro", length = 26)
	public Date getFregistro() {
		return this.fregistro;
	}

	public void setFregistro(Date fregistro) {
		this.fregistro = fregistro;
	}

	@Column(name = "nombres")
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
