package entidades;
// Generated 16/11/2019 11:28:39 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "BtB9DLrhnQ")
public class Empresa implements java.io.Serializable {

	private short id;
	private String nitEmpresa;
	private String razonSocialEmpresa;
	private String telefonosEmpresa;
	private String correoEmpresa;
	private String direccionEmpresa;
	private String estadoEmpresa;

	public Empresa() {
	}

	public Empresa(short id, String nitEmpresa, String razonSocialEmpresa, String telefonosEmpresa,
			String correoEmpresa, String direccionEmpresa, String estadoEmpresa) {
		this.id = id;
		this.nitEmpresa = nitEmpresa;
		this.razonSocialEmpresa = razonSocialEmpresa;
		this.telefonosEmpresa = telefonosEmpresa;
		this.correoEmpresa = correoEmpresa;
		this.direccionEmpresa = direccionEmpresa;
		this.estadoEmpresa = estadoEmpresa;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "nitEmpresa", nullable = false, length = 20)
	public String getNitEmpresa() {
		return this.nitEmpresa;
	}

	public void setNitEmpresa(String nitEmpresa) {
		this.nitEmpresa = nitEmpresa;
	}

	@Column(name = "razonSocialEmpresa", nullable = false, length = 40)
	public String getRazonSocialEmpresa() {
		return this.razonSocialEmpresa;
	}

	public void setRazonSocialEmpresa(String razonSocialEmpresa) {
		this.razonSocialEmpresa = razonSocialEmpresa;
	}

	@Column(name = "telefonosEmpresa", nullable = false, length = 60)
	public String getTelefonosEmpresa() {
		return this.telefonosEmpresa;
	}

	public void setTelefonosEmpresa(String telefonosEmpresa) {
		this.telefonosEmpresa = telefonosEmpresa;
	}

	@Column(name = "correoEmpresa", nullable = false, length = 60)
	public String getCorreoEmpresa() {
		return this.correoEmpresa;
	}

	public void setCorreoEmpresa(String correoEmpresa) {
		this.correoEmpresa = correoEmpresa;
	}

	@Column(name = "direccionEmpresa", nullable = false, length = 60)
	public String getDireccionEmpresa() {
		return this.direccionEmpresa;
	}

	public void setDireccionEmpresa(String direccionEmpresa) {
		this.direccionEmpresa = direccionEmpresa;
	}

	@Column(name = "estadoEmpresa", nullable = false, length = 1)
	public String getEstadoEmpresa() {
		return this.estadoEmpresa;
	}

	public void setEstadoEmpresa(String estadoEmpresa) {
		this.estadoEmpresa = estadoEmpresa;
	}

}
