package entidades;
// Generated 16/11/2019 11:28:39 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name = "movimiento", catalog = "BtB9DLrhnQ")
public class Movimiento implements java.io.Serializable {

	private int id;
	private String placa;
	private String correoUsuario;
	private String tipoParqueadero;
	private Date fechaHoraReserva;
	private Date fechaHoraLlegada;
	private Date fechaHoraSalida;
	private Date tiempo;
	private int valorCobro;
	private int tipoCobro;
	private String activo;

	public Movimiento() {
	}

	public Movimiento(int id, String placa, String correoUsuario, String tipoParqueadero, Date fechaHoraReserva, Date fechaHoraLlegada,
			Date fechaHoraSalida, Date tiempo, int valorCobro, int tipoCobro, String activo) {
		this.id = id;
		this.placa = placa;
		this.correoUsuario = correoUsuario;
		this.tipoParqueadero = tipoParqueadero;
		this.fechaHoraReserva = fechaHoraReserva;
		this.fechaHoraLlegada = fechaHoraLlegada;
		this.fechaHoraSalida = fechaHoraSalida;
		this.tiempo = tiempo;
		this.valorCobro = valorCobro;
		this.tipoCobro = tipoCobro;
		this.activo = activo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "placa", nullable = false, length = 6)
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}
	@Column(name = "correoUsuario", nullable = false, length = 30)
	public String getCorreoUsuario() {
		return correoUsuario;
	}

	public void setCorreoUsuario(String correoUsuario) {
		this.correoUsuario = correoUsuario;
	}

	@Column(name = "tipoParqueadero", nullable = false, length = 20)
	public String getTipoParqueadero() {
		return this.tipoParqueadero;
	}

	public void setTipoParqueadero(String tipoParqueadero) {
		this.tipoParqueadero = tipoParqueadero;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaHoraReserva", nullable = false, length = 19)
	public Date getFechaHoraReserva() {
		return this.fechaHoraReserva;
	}

	public void setFechaHoraReserva(Date fechaHoraReserva) {
		this.fechaHoraReserva = fechaHoraReserva;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaHoraLlegada", nullable = false, length = 19)
	public Date getFechaHoraLlegada() {
		return this.fechaHoraLlegada;
	}

	public void setFechaHoraLlegada(Date fechaHoraLlegada) {
		this.fechaHoraLlegada = fechaHoraLlegada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaHoraSalida", nullable = false, length = 19)
	public Date getFechaHoraSalida() {
		return this.fechaHoraSalida;
	}

	public void setFechaHoraSalida(Date fechaHoraSalida) {
		this.fechaHoraSalida = fechaHoraSalida;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tiempo", nullable = false, length = 8)
	public Date getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(Date tiempo) {
		this.tiempo = tiempo;
	}

	@Column(name = "valorCobro", nullable = false)
	public int getValorCobro() {
		return this.valorCobro;
	}

	public void setValorCobro(int valorCobro) {
		this.valorCobro = valorCobro;
	}

	@Column(name = "tipoCobro", nullable = false)
	public int getTipoCobro() {
		return this.tipoCobro;
	}

	public void setTipoCobro(int tipoCobro) {
		this.tipoCobro = tipoCobro;
	}

	@Column(name = "activo", nullable = false, length = 1)
	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

}
