package entidades;
// Generated 16/11/2019 11:28:39 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name = "parametro", catalog = "BtB9DLrhnQ")
public class Parametro implements java.io.Serializable {

	private int id;
	private String nombreParametro;
	private String descripcion;
	private String valorTexto;
	private int valorNumerico;
	private String estado;

	public Parametro() {
	}

	public Parametro(int id, String nombreParametro, String descripcion, String valorTexto, int valorNumerico,
			String estado) {
		this.id = id;
		this.nombreParametro = nombreParametro;
		this.descripcion = descripcion;
		this.valorTexto = valorTexto;
		this.valorNumerico = valorNumerico;
		this.estado = estado;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombreParametro", nullable = false, length = 15)
	public String getNombreParametro() {
		return this.nombreParametro;
	}

	public void setNombreParametro(String nombreParametro) {
		this.nombreParametro = nombreParametro;
	}

	@Column(name = "descripcion", nullable = false, length = 80)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "valorTexto", nullable = false, length = 20)
	public String getValorTexto() {
		return this.valorTexto;
	}

	public void setValorTexto(String valorTexto) {
		this.valorTexto = valorTexto;
	}

	@Column(name = "valorNumerico", nullable = false)
	public int getValorNumerico() {
		return this.valorNumerico;
	}

	public void setValorNumerico(int valorNumerico) {
		this.valorNumerico = valorNumerico;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
