package entidades;
// Generated 16/11/2019 11:28:39 AM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name = "reserva", catalog = "BtB9DLrhnQ")
public class Reserva implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private String placa;
	private String correoUsuario;
	private String tipoServicio;
	private String tipoParqueadero;
	private String nombreParqueadero;
	private Date fechaHoraReserva;
	private Date fechaHoraLlegada;
	private Date tiempoEstimado;
	private int valorCobro;
	private int tipoCobro;
	private String activo;

	public Reserva() {
	}

	public Reserva(int id, String placa, String correoUsuario, String tipoServicio, String tipoParqueadero,String nombreParqueadero, Date fechaHoraReserva, Date fechaHoraLlegada, Date tiempoEstimado,
			int valorCobro, int tipoCobro, String activo) {
		this.id = id;
		this.placa = placa;
		this.correoUsuario = correoUsuario;
		this.tipoServicio = tipoServicio;
		this.tipoParqueadero  = tipoParqueadero;
		this.nombreParqueadero = nombreParqueadero;
		this.fechaHoraReserva = fechaHoraReserva;
		this.fechaHoraLlegada = fechaHoraLlegada;
		this.tiempoEstimado = tiempoEstimado;
		this.valorCobro = valorCobro;
		this.tipoCobro = tipoCobro;
		this.activo = activo;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tipoServicio", nullable = false, length = 20)
	public String getTipoServicio() {
		return this.tipoServicio;
	}

	public void setTipoServicio(String tipoServicio) {
		this.tipoServicio = tipoServicio;
	}
	
	@Column(name = "nombreParqueadero", nullable = false, length = 30)
	public String getNombreParqueadero() {
		return nombreParqueadero;
	}

	public void setNombreParqueadero(String nombreParqueadero) {
		this.nombreParqueadero = nombreParqueadero;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaHoraReserva", nullable = false, length = 19)
	public Date getFechaHoraReserva() {
		return this.fechaHoraReserva;
	}

	public void setFechaHoraReserva(Date fechaHoraReserva) {
		this.fechaHoraReserva = fechaHoraReserva;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaHoraLlegada", nullable = false, length = 19)
	public Date getFechaHoraLlegada() {
		return this.fechaHoraLlegada;
	}

	public void setFechaHoraLlegada(Date fechaHoraLlegada) {
		this.fechaHoraLlegada = fechaHoraLlegada;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tiempoEstimado", nullable = false, length = 8)
	public Date getTiempoEstimado() {
		return this.tiempoEstimado;
	}

	public void setTiempoEstimado(Date tiempoEstimado) {
		this.tiempoEstimado = tiempoEstimado;
	}

	@Column(name = "valorCobro", nullable = false)
	public int getValorCobro() {
		return this.valorCobro;
	}

	public void setValorCobro(int valorCobro) {
		this.valorCobro = valorCobro;
	}

	@Column(name = "tipoCobro", nullable = false)
	public int getTipoCobro() {
		return this.tipoCobro;
	}

	public void setTipoCobro(int tipoCobro) {
		this.tipoCobro = tipoCobro;
	}

	@Column(name = "activo", nullable = false, length = 1)
	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}
	@Column(name = "placa", nullable = false, length = 6)
	public String getPlaca() {
		return placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	@Column(name = "correoUsuario", nullable = false, length = 30)
	public String getCorreoUsuario() {
		return correoUsuario;
	}

	public void setCorreoUsuario(String correoUsuario) {
		this.correoUsuario = correoUsuario;
	}
	@Column(name = "tipoParqueadero", nullable = false, length = 30)
	public String getTipoParqueadero() {
		return tipoParqueadero;
	}

	public void setTipoParqueadero(String tipoParqueadero) {
		this.tipoParqueadero = tipoParqueadero;
	}
	
	
	

}
