package entidades;
// Generated 16/11/2019 11:28:39 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tarifa generated by hbm2java
 */
@Entity
@Table(name = "tarifa", catalog = "BtB9DLrhnQ")
public class Tarifa implements java.io.Serializable {

	private int id;
	private String descripcionTipoCobro;
	private int valorTarifa;
	private int descuento;
	private String estado;

	public Tarifa() {
	}

	public Tarifa(int id, String descripcionTipoCobro, int valorTarifa, int descuento, String estado) {
		this.id = id;
		this.descripcionTipoCobro = descripcionTipoCobro;
		this.valorTarifa = valorTarifa;
		this.descuento = descuento;
		this.estado = estado;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "descripcionTipoCobro", nullable = false, length = 30)
	public String getDescripcionTipoCobro() {
		return this.descripcionTipoCobro;
	}

	public void setDescripcionTipoCobro(String descripcionTipoCobro) {
		this.descripcionTipoCobro = descripcionTipoCobro;
	}

	@Column(name = "valorTarifa", nullable = false)
	public int getValorTarifa() {
		return this.valorTarifa;
	}

	public void setValorTarifa(int valorTarifa) {
		this.valorTarifa = valorTarifa;
	}

	@Column(name = "descuento", nullable = false)
	public int getDescuento() {
		return this.descuento;
	}

	public void setDescuento(int descuento) {
		this.descuento = descuento;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
