package entidades;
// Generated 16/11/2019 11:28:39 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "BtB9DLrhnQ")
public class Usuario implements java.io.Serializable {

	/*@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)*/
	private Integer id;
	private String login;
	private String clave;
	private String tcredito;
	private String cvv;
	private String apellidosNombres;
	private String correo;
	private String celular;
	private String direccion;
	private Date fechaUltimoPassword;
	private String activo;
	private int intentos;
	private String tipoUsuario;
	private String apellido;
	private Date fechaPassword;
	private Integer intentosPassword;
	private String nombre;
	private String password;

	public Usuario() {
	}

	public Usuario(String login, String clave, String tcredito, String cvv, String apellidosNombres, String correo, String celular,
			String direccion, Date fechaUltimoPassword, String activo, int intentos, String tipoUsuario) {
		this.login = login;
		this.clave = clave;
		this.tcredito = tcredito;
		this.cvv = cvv;
		this.apellidosNombres = apellidosNombres;
		this.correo = correo;
		this.celular = celular;
		this.direccion = direccion;
		this.fechaUltimoPassword = fechaUltimoPassword;
		this.activo = activo;
		this.intentos = intentos;
		this.tipoUsuario = tipoUsuario;
	}

	public Usuario(String login, String clave, String tcredito, String cvv, String apellidosNombres, String correo, String celular,
			String direccion, Date fechaUltimoPassword, String activo, int intentos, String tipoUsuario,
			String apellido, Date fechaPassword, Integer intentosPassword, String nombre, String password) {
		this.login = login;
		this.clave = clave;
		this.tcredito = tcredito;
		this.cvv = cvv;
		this.apellidosNombres = apellidosNombres;
		this.correo = correo;
		this.celular = celular;
		this.direccion = direccion;
		this.fechaUltimoPassword = fechaUltimoPassword;
		this.activo = activo;
		this.intentos = intentos;
		this.tipoUsuario = tipoUsuario;
		this.apellido = apellido;
		this.fechaPassword = fechaPassword;
		this.intentosPassword = intentosPassword;
		this.nombre = nombre;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "login", nullable = false, length = 8)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "clave", nullable = false, length = 256)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "tcredito", nullable = false, length = 30)
	public String getTcredito() {
		return this.tcredito;
	}

	public void setTcredito(String tcredito) {
		this.tcredito = tcredito;
	}
	
	@Column(name = "cvv", nullable = false, length = 30)
	public String getCvv() {
		return this.cvv;
	}

	public void setCvv(String cvv) {
		this.cvv = cvv;
	}

	@Column(name = "apellidosNombres", nullable = false, length = 80)
	public String getApellidosNombres() {
		return this.apellidosNombres;
	}

	public void setApellidosNombres(String apellidosNombres) {
		this.apellidosNombres = apellidosNombres;
	}

	@Column(name = "correo", nullable = false, length = 75)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "celular", nullable = false, length = 15)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "direccion", nullable = false, length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaUltimoPassword", nullable = false, length = 19)
	public Date getFechaUltimoPassword() {
		return this.fechaUltimoPassword;
	}

	public void setFechaUltimoPassword(Date fechaUltimoPassword) {
		this.fechaUltimoPassword = fechaUltimoPassword;
	}

	@Column(name = "activo", nullable = false, length = 1)
	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	@Column(name = "intentos", nullable = false)
	public int getIntentos() {
		return this.intentos;
	}

	public void setIntentos(int intentos) {
		this.intentos = intentos;
	}

	@Column(name = "tipoUsuario", nullable = false, length = 7)
	public String getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(String tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Column(name = "apellido")
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaPassword", length = 26)
	public Date getFechaPassword() {
		return this.fechaPassword;
	}

	public void setFechaPassword(Date fechaPassword) {
		this.fechaPassword = fechaPassword;
	}

	@Column(name = "intentosPassword")
	public Integer getIntentosPassword() {
		return this.intentosPassword;
	}

	public void setIntentosPassword(Integer intentosPassword) {
		this.intentosPassword = intentosPassword;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
