package entidades;
// Generated 16/11/2019 11:28:39 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "vehiculo", catalog = "BtB9DLrhnQ", uniqueConstraints = @UniqueConstraint(columnNames = "id"))
public class Vehiculo implements java.io.Serializable {

	private String placa;
	private int id;
	private String tipo;
	private String marca;
	private int modelo;
	private String color;
	private String estado;
	private String correoUsuario;

	public Vehiculo() {
	}

	public Vehiculo(String placa, int id, String tipo, String marca, int modelo, String color) {
		this.placa = placa;
		this.id = id;
		this.tipo = tipo;
		this.marca = marca;
		this.modelo = modelo;
		this.color = color;
	}

	public Vehiculo(String placa, int id, String tipo, String marca, int modelo, String color, String estado,String correoUsuario) {
		this.placa = placa;
		this.id = id;
		this.tipo = tipo;
		this.marca = marca;
		this.modelo = modelo;
		this.color = color;
		this.estado = estado;
		this.correoUsuario  = correoUsuario;
	}

	@Id

	@Column(name = "placa", unique = true, nullable = false, length = 6)
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tipo", nullable = false, length = 6)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "marca", nullable = false, length = 12)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "modelo", nullable = false)
	public int getModelo() {
		return this.modelo;
	}

	public void setModelo(int modelo) {
		this.modelo = modelo;
	}

	@Column(name = "color", nullable = false, length = 10)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
	@Column(name = "correoUsuario", length = 30)
	public String getCorreoUsuario() {
		return correoUsuario;
	}

	public void setCorreoUsuario(String correoUsuario) {
		this.correoUsuario = correoUsuario;
	}
	

}
